services:
  auth:
    container_name: auth 
    restart: on-failure
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - PORT=3030
      - THUMBSNAP_KEY=0000257fd074329f238355ce4ffbc200
      - SECRET_JWT=40871d49-21f2-45c9-852e-9d8f52f138ca
      - SECRET_KEY_1=686ff5d3-1043-45b4-810b-244a7b4d2b54
      - SECRET_KEY_2=7d9d2044-ae0f-45f1-95ba-8b05b48da6bb
      - DB_CONNECTION_STRING=mongodb+srv://SHOPPI_API:OcruYE1XihzFNQOU@cluster0.0rmwddp.mongodb.net/SHOPPI?retryWrites=true&w=majority
    build:
      context: ./Auth
    image: shoppiapi.azurecr.io/auth
    expose: ["3030"]
  emailverification:
    container_name: emailverification
    restart: on-failure
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - PORT=3010
      - DB_CONNECTION_STRING=mongodb+srv://SHOPPI_API:OcruYE1XihzFNQOU@cluster0.0rmwddp.mongodb.net/SHOPPI?retryWrites=true&w=majority
      - SECRET_JWT=40871d49-21f2-45c9-852e-9d8f52f138ca
      - MAIL_USER=verify.shopi@gmail.com
      - MAIL_ID_CLIENTE=1002171188840-b748jpkef9791hqj9ld9kn3p44185pla.apps.googleusercontent.com
      - MAIL_SECRET=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
      - MAIL_REFRESH_TOKEN=1//04ZBYvtDxCxh1CgYIARAAGAQSNwF-L9IrvZLUd7YriVwLf-otgBuHE-8NOvBu--TDD0pAt2LGegquUE1nm3ZQxeF22AaPu65IdFc
      - GATEWAY_HOST=localhost
      - GATEWAY_PORT=443
    build:
      context: ./EmailVerification
    image: shoppiapi.azurecr.io/emailverification
    expose: ["3010"] 
  gateway:
    container_name: gateway
    restart: on-failure
    build:
      context: ./Orquestador
    image: shoppiapi.azurecr.io/orquestador
    depends_on:
      - auth
      - emailverification
      - posts
      - update-user
    ports: ["443:443"]
  posts:
    container_name: posts
    restart: on-failure
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - PORT=3040
      - THUMBSNAP_KEY=0000257fd074329f238355ce4ffbc200
      - DB_CONNECTION_STRING=mongodb+srv://SHOPPI_API:OcruYE1XihzFNQOU@cluster0.0rmwddp.mongodb.net/SHOPPI?retryWrites=true&w=majority
    build:
      context: ./PostsAll
    image: shoppiapi.azurecr.io/posts
    expose: ["3040"]
  update-user:
    container_name: update-user
    restart: on-failure
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - PORT=3090
      - DB_CONNECTION_STRING=mongodb+srv://SHOPPI_API:OcruYE1XihzFNQOU@cluster0.0rmwddp.mongodb.net/SHOPPI?retryWrites=true&w=majority
      - THUMBSNAP_KEY=0000257fd074329f238355ce4ffbc200
    depends_on:
      - emailverification
    build:
      context: ./UpdateUser
    image: shoppiapi.azurecr.io/update-user
    expose: ["3090"]
  repetidos:
    container_name: repetidos
    restart: on-failure
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - PORT=3100
      - DB_CONNECTION_STRING=mongodb+srv://SHOPPI_API:OcruYE1XihzFNQOU@cluster0.0rmwddp.mongodb.net/SHOPPI?retryWrites=true&w=majority
      - THUMBSNAP_KEY=0000257fd074329f238355ce4ffbc200
    build:
      context: ./Repetidos
    image: shoppiapi.azurecr.io/repetidos
    expose: ["3100"]