services:
  login:
    container_name: login
    restart: always
    env_file:
      - ./Login/development.env
    image: login_test
    expose: ["3500"]
  register:
    container_name: register
    restart: always
    env_file:
      - ./Register/development.env
    image: register_test
    expose: ["3000"]
  emailverification:
    container_name: emailverification
    restart: always
    env_file:
      - ./EmailVerification/development.env
    image: emailv_test
    expose: ["5000"] 
  gateway:
    container_name: gateway
    restart: always
    build:
      context: ./Orquestador
    ports: ["80:8080"]
    
    
