services:
  login:
    container_name: login
    restart: always
    env_file:
      - ./Login/development.env
    build:
      context: ./Login
    expose: ["3500"]
  register:
    container_name: register
    restart: always
    env_file:
      - ./Register/development.env
    build:
      context: ./Register
    expose: ["3000"]
  emailverification:
    container_name: emailverification
    restart: always
    env_file:
      - ./EmailVerification/development.env
    build:
      context: ./EmailVerification
    expose: ["5000"] 
  gateway:
    container_name: gateway
    restart: always
    build:
      context: ./Orquestador
    ports: ["80:8080"]
    
    
