services:
  login:
    container_name: login 
    restart: on-failure
    env_file:
      - ./Login/development.env
    build:
      context: ./Login
    depends_on:
      - database
    expose: ["3030"]
  register:
    container_name: register
    restart: on-failure
    env_file:
      - ./Register/development.env
    build:
      context: ./Register
    depends_on:
      - database
      - emailverification
    expose: ["3020"]
  emailverification:
    container_name: emailverification
    restart: on-failure
    env_file:
      - ./EmailVerification/development.env
    build:
      context: ./EmailVerification
    depends_on:
      - database
    expose: ["3010"] 
  gateway:
    container_name: gateway
    restart: on-failure
    build:
      context: ./Orquestador
    depends_on:
      - login
      - register
      - emailverification
      - main-posts
      - create-posts
      - delete-posts
      - toggle-posts
      - update-posts
    ports: ["80:8080"]
  database:
    container_name: database
    restart: on-failure
    image: mongo:4.4.6
    expose: ["27017"]
  main-posts:
    container_name: main-posts
    restart: on-failure
    env_file:
      - ./MainPosts/development.env
    build:
      context: ./MainPosts
    depends_on:
      - database
    expose: ["3040"]
  create-posts:
    container_name: create-posts
    restart: on-failure
    env_file:
      - ./Posts/Create/development.env
    depends_on:
      - database
    build:
      context: ./Posts/Create
    expose: ["3050"]
  toggle-posts:
    container_name: toggle-posts
    restart: on-failure
    env_file:
      - ./Posts/Toggle/development.env
    depends_on:
      - database
    build:
      context: ./Posts/Toggle
    expose: ["3080"]
  update-posts:
    container_name: update-posts
    restart: on-failure
    env_file:
      - ./Posts/Update/development.env
    depends_on:
      - database
    build:
      context: ./Posts/Update
    expose: ["3070"]
  delete-posts:
    container_name: delete-posts
    restart: on-failure
    env_file:
      - ./Posts/Delete/development.env
    depends_on:
      - database
    build:
      context: ./Posts/Delete
    expose: ["3060"]
    
